#!/bin/bash

### BEGIN INIT INFO
# Provides:        nucypher-kms
# Required-Start:  $local_fs $remote_fs $network $named $syslog $time
# Required-Stop:   $local_fs $remote_fs $network $named $syslog $time
# Default-Start:   2 3 4 5
# Default-Stop:
# Short-Description: Start/Stop NyCypher kms
### END INIT INFO

LINUX_USER=kms
BIN_PATH=/usr/bin
MOD_NAME=nucypher-kms

pid=`ps -ef | grep java | grep -- '-Dproc_kms' | grep -v grep | awk '{ print $2 }'`

case $1 in
start)
	if [ "${pid}" != "" ]
	then
		echo "NuCypher KMS Service is already running"
		exit 1
	else
		echo "Starting NuCypher KMS."
		/bin/su --login  $LINUX_USER -c "${BIN_PATH}/${MOD_NAME} start"
	fi
	;;
stop)
	if [ "${pid}" != "" ]
	then
		echo "Stopping NuCypher KMS."
		/bin/su --login  $LINUX_USER -c "${BIN_PATH}/${MOD_NAME} stop"
	else
		echo "NuCypher Service is NOT running"
		exit 1
	fi
	;;
restart)
	if [ "${pid}" != "" ]
	then
		echo "Stopping NuCypher KMS."
		/bin/su --login  $LINUX_USER -c "${BIN_PATH}/${MOD_NAME} stop"
		sleep 10
	fi
	echo "Starting NuCypher KMS."
	/bin/su --login  $LINUX_USER -c "${BIN_PATH}/${MOD_NAME} start"
	;;
status)
	if [ "${pid}" != "" ]
	then
		echo "NuCypher Service is  running [pid={$pid}]"
	else
		echo "NuCypher Service is  NOT running."

	fi
	;;
*)
	echo "Invalid argument [$1]; Only start|stop|restart|status are supported."
    exit 1
esac
