#!/bin/bash

NUCYPHER_DIRNAME=${PARCEL_DIRNAME:-"NUCYPHERKMS-0.0.1-1.cdh5.7.1.p0.2"}


export NUCYPHER_KMS_PREFIX="$PARCELS_ROOT/$NUCYPHER_DIRNAME"
export NUCYPHER_KMS_CONF_DIR="$PARCELS_ROOT/$NUCYPHER_DIRNAME/etc/hadoop"

export CDH_HADOOP_HOME="$PARCELS_ROOT/CDH/lib/hadoop/"

export HADOOP_COMMON_HOME="$NUCYPHER_KMS_PREFIX"
export HADOOP_PREFIX="$NUCYPHER_KMS_PREFIX"
export HADOOP_LIBEXEC_DIR="$NUCYPHER_KMS_PREFIX/libexec"